/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import * as generated from "./db-schemas";
export type Public_GroupRole_Enum = z.infer<
  typeof generated.publicGroupRoleSchema
>;
export type Public_SettingNames_Enum = z.infer<
  typeof generated.publicSettingNamesSchema
>;
export type Json = z.infer<typeof generated.jsonSchema>;
export type Public_GroupInvites_Row = z.infer<
  typeof generated.publicGroupInvitesRowSchema
>;
export type Public_GroupInvites_Insert = z.infer<
  typeof generated.publicGroupInvitesInsertSchema
>;
export type Public_GroupInvites_Update = z.infer<
  typeof generated.publicGroupInvitesUpdateSchema
>;
export type Public_GroupInvites_Relationships = z.infer<
  typeof generated.publicGroupInvitesRelationshipsSchema
>;
export type Public_GroupProfiles_Row = z.infer<
  typeof generated.publicGroupProfilesRowSchema
>;
export type Public_GroupProfiles_Insert = z.infer<
  typeof generated.publicGroupProfilesInsertSchema
>;
export type Public_GroupProfiles_Update = z.infer<
  typeof generated.publicGroupProfilesUpdateSchema
>;
export type Public_GroupProfiles_Relationships = z.infer<
  typeof generated.publicGroupProfilesRelationshipsSchema
>;
export type Public_Groups_Row = z.infer<typeof generated.publicGroupsRowSchema>;
export type Public_Groups_Insert = z.infer<
  typeof generated.publicGroupsInsertSchema
>;
export type Public_Groups_Update = z.infer<
  typeof generated.publicGroupsUpdateSchema
>;
export type Public_Profiles_Row = z.infer<
  typeof generated.publicProfilesRowSchema
>;
export type Public_Profiles_Insert = z.infer<
  typeof generated.publicProfilesInsertSchema
>;
export type Public_Profiles_Update = z.infer<
  typeof generated.publicProfilesUpdateSchema
>;
export type Public_Regions_Row = z.infer<
  typeof generated.publicRegionsRowSchema
>;
export type Public_Regions_Insert = z.infer<
  typeof generated.publicRegionsInsertSchema
>;
export type Public_Regions_Update = z.infer<
  typeof generated.publicRegionsUpdateSchema
>;
export type Public_Regions_Relationships = z.infer<
  typeof generated.publicRegionsRelationshipsSchema
>;
export type Public_UserSettings_Row = z.infer<
  typeof generated.publicUserSettingsRowSchema
>;
export type Public_UserSettings_Insert = z.infer<
  typeof generated.publicUserSettingsInsertSchema
>;
export type Public_UserSettings_Update = z.infer<
  typeof generated.publicUserSettingsUpdateSchema
>;
export type PublicGetUserProfileIdArgs = z.infer<
  typeof generated.publicGetUserProfileIdArgsSchema
>;
export type PublicGetUserProfileIdReturns = z.infer<
  typeof generated.publicGetUserProfileIdReturnsSchema
>;
export type PublicIsGroupMateArgs = z.infer<
  typeof generated.publicIsGroupMateArgsSchema
>;
export type PublicIsGroupMateReturns = z.infer<
  typeof generated.publicIsGroupMateReturnsSchema
>;
export type PublicSoftDeleteRecordArgs = z.infer<
  typeof generated.publicSoftDeleteRecordArgsSchema
>;
export type PublicSoftDeleteRecordReturns = z.infer<
  typeof generated.publicSoftDeleteRecordReturnsSchema
>;
export type PublicUserHasGroupRoleArgs = z.infer<
  typeof generated.publicUserHasGroupRoleArgsSchema
>;
export type PublicUserHasGroupRoleReturns = z.infer<
  typeof generated.publicUserHasGroupRoleReturnsSchema
>;
export type PublicUserIsGroupMemberArgs = z.infer<
  typeof generated.publicUserIsGroupMemberArgsSchema
>;
export type PublicUserIsGroupMemberReturns = z.infer<
  typeof generated.publicUserIsGroupMemberReturnsSchema
>;
