/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as userRouteRouteImport } from './routes/(user)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as GroupSlugRouteRouteImport } from './routes/$groupSlug/route'
import { Route as userIndexRouteImport } from './routes/(user)/index'
import { Route as GroupSlugIndexRouteImport } from './routes/$groupSlug/index'
import { Route as userSettingsRouteImport } from './routes/(user)/settings'
import { Route as userProfileRouteImport } from './routes/(user)/profile'
import { Route as userCreateGroupRouteImport } from './routes/(user)/create-group'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authCreateAccountRouteImport } from './routes/(auth)/create-account'
import { Route as authConfirmEmailRouteImport } from './routes/(auth)/confirm-email'

const userRouteRoute = userRouteRouteImport.update({
  id: '/(user)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupSlugRouteRoute = GroupSlugRouteRouteImport.update({
  id: '/$groupSlug',
  path: '/$groupSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const userIndexRoute = userIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => userRouteRoute,
} as any)
const GroupSlugIndexRoute = GroupSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GroupSlugRouteRoute,
} as any)
const userSettingsRoute = userSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => userRouteRoute,
} as any)
const userProfileRoute = userProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => userRouteRoute,
} as any)
const userCreateGroupRoute = userCreateGroupRouteImport.update({
  id: '/create-group',
  path: '/create-group',
  getParentRoute: () => userRouteRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authCreateAccountRoute = authCreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => authRouteRoute,
} as any)
const authConfirmEmailRoute = authConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => authRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$groupSlug': typeof GroupSlugRouteRouteWithChildren
  '/confirm-email': typeof authConfirmEmailRoute
  '/create-account': typeof authCreateAccountRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/create-group': typeof userCreateGroupRoute
  '/profile': typeof userProfileRoute
  '/settings': typeof userSettingsRoute
  '/$groupSlug/': typeof GroupSlugIndexRoute
  '/': typeof userIndexRoute
}
export interface FileRoutesByTo {
  '/confirm-email': typeof authConfirmEmailRoute
  '/create-account': typeof authCreateAccountRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/create-group': typeof userCreateGroupRoute
  '/profile': typeof userProfileRoute
  '/settings': typeof userSettingsRoute
  '/$groupSlug': typeof GroupSlugIndexRoute
  '/': typeof userIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$groupSlug': typeof GroupSlugRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/(user)': typeof userRouteRouteWithChildren
  '/(auth)/confirm-email': typeof authConfirmEmailRoute
  '/(auth)/create-account': typeof authCreateAccountRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(user)/create-group': typeof userCreateGroupRoute
  '/(user)/profile': typeof userProfileRoute
  '/(user)/settings': typeof userSettingsRoute
  '/$groupSlug/': typeof GroupSlugIndexRoute
  '/(user)/': typeof userIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$groupSlug'
    | '/confirm-email'
    | '/create-account'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/create-group'
    | '/profile'
    | '/settings'
    | '/$groupSlug/'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/confirm-email'
    | '/create-account'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/create-group'
    | '/profile'
    | '/settings'
    | '/$groupSlug'
    | '/'
  id:
    | '__root__'
    | '/$groupSlug'
    | '/(auth)'
    | '/(user)'
    | '/(auth)/confirm-email'
    | '/(auth)/create-account'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/reset-password'
    | '/(user)/create-group'
    | '/(user)/profile'
    | '/(user)/settings'
    | '/$groupSlug/'
    | '/(user)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GroupSlugRouteRoute: typeof GroupSlugRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
  userRouteRoute: typeof userRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(user)': {
      id: '/(user)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof userRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$groupSlug': {
      id: '/$groupSlug'
      path: '/$groupSlug'
      fullPath: '/$groupSlug'
      preLoaderRoute: typeof GroupSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(user)/': {
      id: '/(user)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof userIndexRouteImport
      parentRoute: typeof userRouteRoute
    }
    '/$groupSlug/': {
      id: '/$groupSlug/'
      path: '/'
      fullPath: '/$groupSlug/'
      preLoaderRoute: typeof GroupSlugIndexRouteImport
      parentRoute: typeof GroupSlugRouteRoute
    }
    '/(user)/settings': {
      id: '/(user)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof userSettingsRouteImport
      parentRoute: typeof userRouteRoute
    }
    '/(user)/profile': {
      id: '/(user)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof userProfileRouteImport
      parentRoute: typeof userRouteRoute
    }
    '/(user)/create-group': {
      id: '/(user)/create-group'
      path: '/create-group'
      fullPath: '/create-group'
      preLoaderRoute: typeof userCreateGroupRouteImport
      parentRoute: typeof userRouteRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/create-account': {
      id: '/(auth)/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof authCreateAccountRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/confirm-email': {
      id: '/(auth)/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof authConfirmEmailRouteImport
      parentRoute: typeof authRouteRoute
    }
  }
}

interface GroupSlugRouteRouteChildren {
  GroupSlugIndexRoute: typeof GroupSlugIndexRoute
}

const GroupSlugRouteRouteChildren: GroupSlugRouteRouteChildren = {
  GroupSlugIndexRoute: GroupSlugIndexRoute,
}

const GroupSlugRouteRouteWithChildren = GroupSlugRouteRoute._addFileChildren(
  GroupSlugRouteRouteChildren,
)

interface authRouteRouteChildren {
  authConfirmEmailRoute: typeof authConfirmEmailRoute
  authCreateAccountRoute: typeof authCreateAccountRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authConfirmEmailRoute: authConfirmEmailRoute,
  authCreateAccountRoute: authCreateAccountRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authResetPasswordRoute: authResetPasswordRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface userRouteRouteChildren {
  userCreateGroupRoute: typeof userCreateGroupRoute
  userProfileRoute: typeof userProfileRoute
  userSettingsRoute: typeof userSettingsRoute
  userIndexRoute: typeof userIndexRoute
}

const userRouteRouteChildren: userRouteRouteChildren = {
  userCreateGroupRoute: userCreateGroupRoute,
  userProfileRoute: userProfileRoute,
  userSettingsRoute: userSettingsRoute,
  userIndexRoute: userIndexRoute,
}

const userRouteRouteWithChildren = userRouteRoute._addFileChildren(
  userRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  GroupSlugRouteRoute: GroupSlugRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
  userRouteRoute: userRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
